### ISSUE TITLE
[FEA] custom kernel for URI/URL parsing

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids-jni#1326]
**Is your feature request related to a problem? Please describe.**

https://github.com/NVIDIA/spark-rapids/pull/8761 added URL parsing (Actually URI parsing, spark made the switch a while ago on the backend), but to do it we had to make a regular expression that is crazy big. A lot of that size comes from trying to be IPv6 Compatible.  Really we should write a custom kernel to save memory, and performance.

https://www.rfc-editor.org/rfc/rfc2396 describes the official syntax, but we could probably find/use another Apache licensed URI parser like https://github.com/apache/commons-vfs/blob/master/commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/UriParser.java
```[tasklist]
### Tasks
- [x] https://github.com/NVIDIA/spark-rapids-jni/issues/1500
- [x] https://github.com/NVIDIA/spark-rapids-jni/issues/1501
- [ ] https://github.com/NVIDIA/spark-rapids-jni/issues/1585
- [x] https://github.com/NVIDIA/spark-rapids-jni/issues/1650
- [x] Implement REF url parsing
- [x] Implement FILE url parsing
- [x] Implement AUTHORITY url parsing
- [x] Implement USERINFO url parsing
```

**Comment by thirtiseven** [comment]
[Here](https://gist.github.com/thirtiseven/1c69bbc731ad730ee22513ebeb1388e2) is a direct translation of the URL parsing part of the Java URI lib to C++ that might help this issue.

**Comment by revans2** [comment]
> [Here](https://gist.github.com/thirtiseven/1c69bbc731ad730ee22513ebeb1388e2) is a direct translation of the URL parsing part of the Java URI lib to C++ that might help this issue.

We cannot use that code. The java code is under a GPL license with a classpath exception. Our license is Apache. The two are not compatible with each other. Do not copy any of the java or code from the GIST url above to the kernel we produce or we will have to write it over again from scratch.

**Comment by hyperbolic2346** [comment]
These have been implemented.
