### ISSUE TITLE
Implement QUERY url parsing

### ISSUE THREAD

**Issue by hyperbolic2346** [NVIDIA/spark-rapids-jni#1650]
Adding support for `parse_uri` to return the query is actually comprised of 3 parts: The base query returned, a query that matches a literal returned, and a query that matches a literal from the corresponding row of another column returned.

```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/spark-rapids-jni/issues/1651
- [ ] https://github.com/NVIDIA/spark-rapids-jni/issues/1703
- [ ] https://github.com/NVIDIA/spark-rapids-jni/issues/1718
```
