### ISSUE TITLE
[FEA] GetJsonObject: Implement get-json-object in JNI repo as Spark does

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids-jni#1823]
**Is your feature request related to a problem? Please describe.**

There are some issues for the current `get-json-object`, refer to [issues link](https://github.com/NVIDIA/spark-rapids/issues/10254)
We plan to implement get-json-object as Spark does. Then these issues will be fixed or be easy to be fixed.

**Describe the solution you'd like**
- Implement a JSON parser like Jackson does, supports `ALLOW_UNESCAPED_CONTROL_CHARS` and `ALLOW_SINGLE_QUOTES`
- Implement a Path parser like Spark does
- Implement utilities like Spark does
- Implement get-json-object like Spark does

**tasks**
- [x] https://github.com/NVIDIA/spark-rapids-jni/issues/1827
- [x] https://github.com/NVIDIA/spark-rapids-jni/issues/1829
- [x] https://github.com/NVIDIA/spark-rapids-jni/issues/1856
- [x] https://github.com/NVIDIA/spark-rapids-jni/issues/1830
- [x] https://github.com/NVIDIA/spark-rapids-jni/issues/1831
- [x] https://github.com/NVIDIA/spark-rapids-jni/issues/1848
- [x] https://github.com/NVIDIA/spark-rapids-jni/issues/1832
- [x] https://github.com/NVIDIA/spark-rapids-jni/issues/1882
- [x] https://github.com/NVIDIA/spark-rapids-jni/issues/1885
- [x] https://github.com/NVIDIA/spark-rapids-jni/issues/1886
- [x] https://github.com/NVIDIA/spark-rapids-jni/issues/1892
- [x] Perf test: https://github.com/NVIDIA/spark-rapids-jni/issues/1894
- [x] Merge feature branch to branch-24.04 branch: https://github.com/NVIDIA/spark-rapids-jni/issues/1891
- [x] Investigate number processing diffs between cuDF and Spark, Spark use big decimal, JNI should use big decimal too.  Duplicated with #1831
- [x] revert already merged JSON PR. [link1](https://github.com/NVIDIA/spark-rapids/pull/10522), 
[link2](https://github.com/NVIDIA/spark-rapids/pull/10466).  @thirtiseven 

**other**
Totally follow Spark specific logic of `get-json-object`

**3 follow-up issues for release 24.06**  
Refine doc: https://github.com/NVIDIA/spark-rapids-jni/issues/1905
Address comments: https://github.com/NVIDIA/spark-rapids-jni/issues/1906
Perf: https://github.com/NVIDIA/spark-rapids-jni/issues/1907

**Comment by res-life** [comment]
get-json-object JNI repo PR posted: https://github.com/NVIDIA/spark-rapids-jni/pull/1893

**Comment by res-life** [comment]
Confirmed with @thirtiseven, we do not need to revert [link1](https://github.com/NVIDIA/spark-rapids/pull/10522),
[link2](https://github.com/NVIDIA/spark-rapids/pull/10466), because solution changed, we now are using Java JSON Path parser. So close the last item.

**Comment by res-life** [comment]
Haoyang finished the perf test, refer to the description in [PR](https://github.com/NVIDIA/spark-rapids/pull/10581)

**Comment by res-life** [comment]
Number normalization PR: https://github.com/NVIDIA/spark-rapids-jni/pull/1897

**Comment by res-life** [comment]
The last task is merging the feature branch to branch-24.04.
